"""Tuppu AST node definitions.

Every node carries optional `line` and `col` attributes (source position)
as keyword-only fields. They default to 0 and are excluded from equality,
so existing structural comparisons in tests still work as before.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Union


# Shared position field spec. kw_only=True keeps positional constructors
# working. compare=False keeps equality based on semantic content only.
def _pos():
    return field(default=0, kw_only=True, compare=False, repr=False)


# --- types in source ---------------------------------------------------------

@dataclass
class TypeName:
    name: str                        # "i64", "bool", "rat", or a struct name
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeArray:
    size: int
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeTablets:
    size: int
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeBuffer:
    """`buffer[N]T` — a fixed-size, stack-allocated, bounds-checked
    buffer of T. Intended for byte-level FFI (`buffer[1024]u8`) and
    any other place where you want a slab of `N` elements with
    C-ABI pointer decay at the FFI boundary. Distinct from
    `tablets[N]T` (which is a growable chunked storage) and from the
    old `[N]T` shape that was retired when `str` landed.
    Return type and struct-field placement are rejected at typecheck
    (would dangle / need ownership semantics we don't have)."""
    size: int
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeVariadicTablets:
    """`tablets[...]T` — a last-param shape that collects the trailing
    call-site args into a synthetic TabletsLit. Inside a fn body a
    binding of this type behaves like a regular `tablets[N]T` for
    indexing, iteration, and method dispatch."""
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypePointer:
    """A raw (unmanaged) pointer type, spelled `*T` in source.

    Intentionally restricted: pointers can be held and passed around,
    but have no expression-level dereference, arithmetic, or
    construction syntax. Their role is to let `str` describe itself
    (`seal str { ptr: *u8, len: i64 }`) and to interoperate with
    compiler-generated byte-level operations. Adding user-side deref
    or arithmetic requires an unsafe-block decision we haven't made."""
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeHandle:
    """`wedge T` — a handle into some `tablets[N]T`. A single-slot
    reference; in runtime terms a pointer to the element slot inside
    a tablets chunk. Obtained by `tablets.push(...)` (returns the
    handle to the newly pushed element). Compared for equality with
    `==` / `!=`. The special value `lost` represents "no tablet"
    (internally a null pointer)."""
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeIVec:
    """`ivec<T>` — indirect vector. Contiguous heap-allocated array of
    pointers to per-element T allocations. Random access is O(1) (two
    loads), and resize moves only the pointer array, leaving each T's
    address stable for the lifetime of the surrounding ivec. Companion
    type `dvec<T>` (planned) will store T values inline for primitive
    T at the cost of pointer-instability across grow."""
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeDVec:
    """`dvec<T>` — direct vector. Contiguous heap-allocated array of T
    values stored inline. O(1) random access (one load). Grow
    invalidates element addresses (memcpy moves inline T bytes), so
    `push` returns unit rather than a handle. Best for primitive /
    small T where the per-element heap allocation that ivec needs is
    wasteful."""
    element: "TypeExpr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TypeFn:
    """First-class function type: `fn(T1, T2) -> U`. No environment —
    these are plain function pointers (capture comes later). Used in
    param / binding / return annotations; when a bare fn name appears
    as an expression, its type is this shape."""
    params: list["TypeExpr"]
    return_type: "TypeExpr | None"
    line: int = _pos()
    col:  int = _pos()


@dataclass
class TypeApply:
    """A parameterized type application like `List<i64>` or `Node<T>`.
    `name` is the user-defined tablet name; `args` is the list of
    instantiated type arguments (each itself a TypeExpr). Only valid
    in type positions, never in expression positions — the parser
    never allows `Foo<bar>` to appear where it could ambiguate with
    comparison."""
    name: str
    args: list["TypeExpr"]
    line: int = _pos()
    col:  int = _pos()

TypeExpr = Union[
    TypeName, TypeArray, TypeTablets, TypeBuffer, TypeVariadicTablets,
    TypePointer, TypeHandle, TypeIVec, TypeDVec, TypeApply, TypeFn,
]


# --- expressions -------------------------------------------------------------

@dataclass
class IntLit:
    value: int
    line: int = _pos()
    col:  int = _pos()

@dataclass
class SexLit:
    """A sexagesimal literal — preserves the original Babylonian digit
    sequence and pre-reduces it to rat form for arithmetic.

    int_digits: pre-radix digits (may be empty for literals like `;30`,
        though the current lexer requires a leading digit).
    frac_digits: post-radix digits, or None for pure integer-form sex
        (e.g. `1 30` with no `;`).
    num / den: the exact rational this literal denotes (lexer pre-reduces).
    """
    int_digits: list[int]
    frac_digits: list[int] | None
    num: int
    den: int
    line: int = _pos()
    col:  int = _pos()

@dataclass
class StringLit:
    value: bytes
    line: int = _pos()
    col:  int = _pos()

@dataclass
class CharLit:
    """A single-byte character literal like `'a'` (97) or `'\\n'` (10).
    Type is always u8."""
    value: int
    line: int = _pos()
    col:  int = _pos()

@dataclass
class BoolLit:
    value: bool
    line: int = _pos()
    col:  int = _pos()

@dataclass
class LostLit:
    """The null handle — `lost` in source. Types to `tablet T` for any
    T via implicit coercion; standalone it has a fresh open type that
    gets unified at its use site."""
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Ident:
    name: str
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Unary:
    op: str                          # "-" or "!"
    operand: "Expr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Binary:
    op: str
    lhs: "Expr"
    rhs: "Expr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Call:
    callee: "Expr"
    args: list["Expr"]
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Index:
    target: "Expr"
    index: "Expr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Field:
    target: "Expr"
    name: str
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Slice:
    """A Python-style slice expression: `s[lo:hi]`, `s[:hi]`, `s[lo:]`,
    or `s[:]`. Either bound may be `None`, in which case codegen fills
    in `0` / `s.len` respectively. Distinct from `Index` — an `Index`
    always has a single non-optional subscript."""
    target: "Expr"
    lo: "Expr | None"
    hi: "Expr | None"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Cast:
    value: "Expr"
    type: TypeExpr
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Copy:
    """`copy expr` — deep-clones a cleanup-bearing value into independent
    ownership. Typechecks as `T -> T` on any cleanup-bearing type; lowers
    to the same `_deep_clone_if_cleanup_bearing` the codegen already uses
    for return/push/assign paths, with an rvalue cleanup registered at
    the consumer site."""
    value: "Expr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class StructLit:
    """A struct literal: `Point { x: 3, y: 4 }`. Fields are stored in parse
    order; the type checker reconciles them against the declaration."""
    name: str
    fields: list[tuple[str, "Expr"]]
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TabletsLit:
    """`tablets[N]T { a, b, c }` — constructs a pre-populated tablets
    value in one expression. Size is required when spelled; the
    synthetic literal the parser produces for variadic call arguments
    uses a compiler-chosen canonical size. element may be None when
    the checker is expected to infer it from context (variadic call
    desugaring). fields are expressions, evaluated left-to-right."""
    size: int
    element: "TypeExpr | None"
    fields: list["Expr"]
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Block:
    stmts: list["Stmt"] = field(default_factory=list)
    tail: "Expr | None" = None
    line: int = _pos()
    col:  int = _pos()

@dataclass
class IfExpr:
    cond: "Expr"
    then: Block
    else_: "Block | IfExpr | None" = None
    line: int = _pos()
    col:  int = _pos()


# --- patterns ---------------------------------------------------------------

@dataclass
class WildcardPattern:
    """`_` — matches anything, binds nothing."""
    line: int = _pos()
    col:  int = _pos()

@dataclass
class VariantPattern:
    """`Name` (nullary) or `Name(x, y)` (positional binders). For a
    binder slot, `None` indicates a wildcard position (`Name(_, x)`);
    otherwise it's the name to bind that field to within the arm body."""
    name: str
    binders: list["str | None"]  # None = wildcard at that slot
    line: int = _pos()
    col:  int = _pos()

Pattern = Union[WildcardPattern, VariantPattern]


@dataclass
class MatchArm:
    pattern: Pattern
    body: "Expr"
    line: int = _pos()
    col:  int = _pos()

@dataclass
class MatchExpr:
    """`match scrutinee { pat => expr, ... }` — variant-dispatching
    expression. Exhaustive over the scrutinee's seal variants unless
    a wildcard arm is present."""
    scrutinee: "Expr"
    arms: list[MatchArm]
    line: int = _pos()
    col:  int = _pos()


Expr = Union[
    IntLit, SexLit, StringLit, CharLit, BoolLit, LostLit, Ident,
    Unary, Binary, Call, Index, Slice, Field, Cast, Copy, StructLit,
    TabletsLit, Block, IfExpr, MatchExpr,
]


# --- statements --------------------------------------------------------------

@dataclass
class Binding:
    is_mut: bool
    name: str
    type_ann: TypeExpr | None
    init: Expr | None
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Assign:
    # target is an lvalue expression — either `Ident` (plain variable
    # assign) or a `Field` chain rooted at an Ident (`p.x = 5`,
    # `line.a.x = 5`). The parser enforces this shape.
    target: Expr
    value: Expr
    line: int = _pos()
    col:  int = _pos()

@dataclass
class While:
    cond: Expr
    body: Block
    line: int = _pos()
    col:  int = _pos()

@dataclass
class ForStmt:
    """`for name in iter { body }` — iterates over a str, tablets, or table.
    The loop variable is immutable within each iteration (like a `step`)."""
    name: str
    iter: Expr
    body: Block
    line: int = _pos()
    col:  int = _pos()

@dataclass
class YieldStmt:
    value: Expr | None
    line: int = _pos()
    col:  int = _pos()

@dataclass
class ReleaseStmt:
    name: str
    line: int = _pos()
    col:  int = _pos()

@dataclass
class ExprStmt:
    expr: Expr
    line: int = _pos()
    col:  int = _pos()

Stmt = Union[Binding, Assign, While, ForStmt, YieldStmt, ReleaseStmt, ExprStmt]


# --- top level --------------------------------------------------------------

@dataclass
class Param:
    name: str
    type: TypeExpr
    is_mut: bool = False
    line: int = _pos()
    col:  int = _pos()

@dataclass
class FnDecl:
    name: str
    params: list[Param]
    return_type: TypeExpr | None
    body: Block
    type_params: list[str] = field(default_factory=list)
    line: int = _pos()
    col:  int = _pos()

@dataclass
class TableDecl:
    name: str
    lo: Expr
    hi: Expr
    element_type: TypeExpr
    generator: Expr
    line: int = _pos()
    col:  int = _pos()

@dataclass
class StructDecl:
    """A user-defined tablet (product) type. Fields are stored in parse
    order and are nominally typed — two structurally identical tablets
    with different names do not unify. `type_params` lists the type
    variables introduced by the declaration, e.g. ["T"] for
    `tablet Node<T> { ... }`; empty for non-generic tablets."""
    name: str
    fields: list[tuple[str, TypeExpr]]
    type_params: list[str] = field(default_factory=list)
    line: int = _pos()
    col:  int = _pos()

@dataclass
class Variant:
    """One alternative of a seal: `Some(T)`, `Circle(rat)`, or nullary
    like `None`. Fields are positional (unnamed) — named variant fields
    may come in a later pass."""
    name: str
    fields: list[TypeExpr]
    line: int = _pos()
    col:  int = _pos()

@dataclass
class SealDecl:
    """A user-defined seal (sum) type. Variants are stored in parse
    order. Generic seals (`seal Option<T>`) use the same type-param
    machinery as generic tablets."""
    name: str
    variants: list[Variant]
    type_params: list[str] = field(default_factory=list)
    line: int = _pos()
    col:  int = _pos()

@dataclass
class GlossDecl:
    """An operator-overload declaration: `gloss add(a: Vector, b: Vector)
    -> Vector { ... }`. The scribe's gloss — a marginal note that
    assigns meaning to a symbol. Parses like `fn` but with a fixed
    set of op names (`add`, `sub`, `mul`, `div`, `mod`, `eq`, `lt`,
    `le`, `gt`, `ge`, `neg`, `not`). Registered in a dispatch table
    keyed by (op, lhs_ty, rhs_ty); binary/unary ops on user types
    look up the table before erroring. Internal LLVM symbol gets a
    `__gloss_<op>_<lhs>_<rhs>` mangling so users retain full freedom
    over the plain `add` / `eq` namespace."""
    op: str                     # one of the fixed gloss op names
    params: list[Param]
    return_type: TypeExpr | None
    body: Block
    line: int = _pos()
    col:  int = _pos()

@dataclass
class ColophonDecl:
    """An external declaration — the Tuppu scribe's pointer at a
    function that lives outside the tablet. Parses like `fn` but has
    no body. The compiler emits an LLVM extern and marshals args /
    returns at each call site: `str` ↔ NUL-terminated cstring, ints
    and bools pass directly. No type parameters (C has no generics),
    no variadics (defer), no raw pointers in the signature —
    everything that crosses the boundary is already a value type the
    rest of Tuppu knows how to hold."""
    name: str
    params: list[Param]
    return_type: TypeExpr | None
    # Optional C symbol override — `colophon fn rename(...) = "real_c_name"(...)`
    # is a future shape; for now `c_name` defaults to `name` at parse time.
    c_name: str = ""
    line: int = _pos()
    col:  int = _pos()


@dataclass
class AliasDecl:
    """A type alias: `type Bytes = buffer[1024]u8`. The alias name
    refers to the underlying type expression at every use site;
    aliases never form a new nominal type (so an `alias` of a tablet
    unifies with the tablet itself and any other alias of it). Type
    params are deferred to a future pass — `type Pair<T> = (T, T)`
    would need first-class tuples we don't have yet."""
    name: str
    target: TypeExpr
    line: int = _pos()
    col:  int = _pos()


@dataclass
class ImportDecl:
    """A top-level import: brings public names from another module into
    the current file's scope. Three surface forms:

      `import x.y`            — wildcard: every public name from x.y
                                becomes available unqualified in this
                                file (equivalent to `from x.y import *`).
      `import x.y as z`       — wildcard with a prefix on every imported
                                name (`z_<name>`)? Reserved for future;
                                currently rejected with a clear error.
      `from x.y import a, b`  — pull just `a` and `b` into this file.
      `from x.y import a as a2`
                              — same, with a local rename.

    `path` is the module path as a list of segments (`["stdlib", "list"]`
    for `stdlib.list`). `names` is None for the wildcard form, or a list
    of (source_name, local_alias_or_None) pairs for the `from` form.
    `wildcard_alias` is reserved for the future `import x as z` form."""
    path: list[str]
    names: list[tuple[str, "str | None"]] | None
    wildcard_alias: "str | None" = None
    line: int = _pos()
    col:  int = _pos()


@dataclass
class EdubbaDecl:
    """A methods block: `edubba Map<T> { fn set(mut self, k, v) {...} }`.
    E-DUB-BA-A was the Sumerian/Akkadian scribal school where students
    learned to read, write, and work with tablets — so the edubba of a
    type collects its operations.

    Each method's first param is implicit `self` (or `mut self`); the
    parser materializes the receiver `Param` from `type_name` +
    `type_params`. Methods are otherwise plain `FnDecl`s — the body is
    type-checked and codegen'd through the same path as any free fn,
    just with a mangled name (`<TypeName>__<method>`).

    Multiple edubba blocks per tablet are allowed; they're additive."""
    type_name: str
    type_params: list[str]
    methods: list[FnDecl]
    line: int = _pos()
    col:  int = _pos()


Decl = Union[
    FnDecl, TableDecl, StructDecl, SealDecl, ColophonDecl, GlossDecl, EdubbaDecl, AliasDecl,
    ImportDecl,
]

@dataclass
class Program:
    decls: list[Decl] = field(default_factory=list)
    # Module-of-decl sideband. Keyed by `id(decl)`, value is the dotted
    # module path the decl was declared in (e.g. `("stdlib", "list")`).
    # Decls without an entry — including built-in injections like the
    # `str` tablet, and any decls produced by a single-source compile
    # path that doesn't go through the file driver — live in the root
    # module (empty tuple). The driver populates this when bundling
    # multiple files; later phases (typecheck visibility checks, codegen
    # mangling) consult it but tolerate missing keys.
    module_of: dict[int, tuple[str, ...]] = field(default_factory=dict, compare=False, repr=False)
